### ISSUE TITLE
Log primero case_id or record_id (both if available)

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#12]
After we upload a case to Primero (see example run: https://www.openfn.org/projects/p5am6e/runs/rd7e8mx9)... please log the Primero `case_id` or `record_id` (or both if available). I know that Primero will provide this in its response to our POST http requests. 

## expression
https://github.com/OpenFn/primero-progres/blob/master/jobs/1.upsertExtracts.js

## adaptor
primer

## state
https://www.openfn.org/projects/p5am6e/messages/m78napnq
Please feel free to run on prod. See LP for `Dadaab open_function user`

**Comment by aleksa-krolls** [comment]
@lakhassane I think a very quick one if you have time before signing off today!

**Comment by lakhassane** [comment]
@aleksa-krolls done.
Check log at line `64` https://www.openfn.org/projects/p5am6e/runs/ryakeg6e

**Comment by aleksa-krolls** [comment]
amazing, thanks!
