### ISSUE TITLE
Add date filter to Primero `getCases(...)` query

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#14]
## Background
See issue #5 for background on the Primero --> DTP/Progres referral flow. 

## Request
In this other job, we added a query filter to only get cases updated in the last 24 hours (see below). 
https://github.com/OpenFn/primero-progres/blob/5dc8b58b6784f4b998c193a0eb9e365b955332db/jobs/1.b.sendReferrals.js#L6-L15

**Can we please add this data query into the `2.a.getCases.js` job to also filter by `last_updated_at= last 24hrs`?** 
But please keep the existing filter criteria we already have implemented (see below). 
https://github.com/OpenFn/primero-progres/blob/918ba1c54f653000f4a15270b26877ff878249a6/jobs/2.a.getCases.js#L1-L13

## expression
https://github.com/OpenFn/primero-progres/blob/master/jobs/2.a.getCases.js
(This is a flow job that gets data from Primero, and then triggers `2.b.uploadReferrals.js` to send to DTP)

## state
See LP for Primero Dadaab

**Comment by lakhassane** [comment]
Now @aleksa-krolls Im not sure what was done in `sendReferrals`is working.
If we want to **filter** by `last_updated_at` we need that as a key and not query.
But filtering by last_updated_at returns only the cases of that day and not of the last 24h and I can't find in the documentation anywhere primero allows to do that.

Is it still possible to ask them clear use cases example?

**Comment by aleksa-krolls** [comment]
@lakhassane Not possible... so please filter where `last_updated_at === today()` and we will time the job to run daily.

**Comment by lakhassane** [comment]
@aleksa-krolls it's done. I corrected the same for `sendReferrals`

**Comment by aleksa-krolls** [comment]
@lakhassane Can you please make sure that `today()` always has a timestamp of `00:00`? (e.g., `2021-05-31 00:00`) Right now we're returning the current timestamp

**Comment by lakhassane** [comment]
it's set @aleksa-krolls so right now here is the query we are returning
```
query {
  remote: true,
  assigned_user_names: [ 'unhcr_cw' ],
  last_updated_at: '2021-06-01T00:00:00.000Z' (being set programatically)
}
```
