### ISSUE TITLE
 Field mapping not returning value `unhcr_id_no: undefined`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#18]
## Bug
See [this run](https://www.openfn.org/projects/p5am6e/runs/rx85kke4) - L22: `unhcr_id_no: undefined`. However, the source value is available in state and the job mapping looks right to me... what do you think is going on? 
(This might be affecting other mappings too, if it is an issue)

## expression
https://github.com/OpenFn/primero-progres/blob/0c6801fb13ae5f778269607de6595c6c155fab40/jobs/1.upsertExtracts.js#L440

## state
See L14 for the source value I expect to be returned: `UGA-19-00009`
https://www.openfn.org/projects/p5am6e/messages/mmq5g67g

## To test
Please feel free to re-run this on prod: https://www.openfn.org/projects/p5am6e/messages/mmq5g67g

**Comment by aleksa-krolls** [comment]
@lakhassane Let me know if this can be addressed before 10:30a Senegal time. (UNHCR is starting a testing session then, so I need to let them know if the bug has been resolved.)

**Comment by lakhassane** [comment]
@aleksa-krolls I made the corrections: https://www.openfn.org/projects/p5am6e/runs/r3xmrgge
