### ISSUE TITLE
Flow 2: Primero referral to DTP fails

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#19]
## Bug
See [this run](https://www.openfn.org/projects/p5am6e/runs/rx85y57p) ... we need to handle for scenarios where `language` and `protection_concerns` might not be defined in primero... if that's the case, then we return `null` in the mapping when sending to DTP

## expression
https://github.com/OpenFn/primero-progres/blob/master/jobs/2.b.uploadReferrals.js

## state
https://www.openfn.org/projects/p5am6e/messages/mj45kk69

## To test
Please feel free to re-run this on prod: https://www.openfn.org/projects/p5am6e/messages/mj45kk69

**Comment by lakhassane** [comment]
Correction made: https://www.openfn.org/projects/p5am6e/runs/rwapnygn
