### ISSUE TITLE
Flow1-1. Send Referrals to Primero --> upsert 1st matching case

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#22]
## Request 
In this job we search for existing Primero cases for `unhcr_individual_no` before upserting the case with referral info. 

See this run where 6 matching Primero cases are found... this is because of bad test data, so shouldn't happen in real life... but please upsert the first matching Primero case found, if multiple. 
https://www.openfn.org/projects/p5am6e/runs/r5e6yg5r

## state
Please re-run all of these Messages in prod to make sure they run successfully. 
https://www.openfn.org/projects/p5am6e/messages?endDate=2021-06-04T13%3A44%3A29.354Z&jobStates=fail&startDate=2021-06-03T13%3A44%3A29.375Z&triggerId=t9vj34

## expresssion
https://github.com/OpenFn/primero-progres/blob/4bbef6a536340f44a657d3455935a1a5471fb21b/jobs/1.upsertExtracts.js#L469-L472

**Comment by lakhassane** [comment]
@aleksa-krolls I updated the job as specified. However primero keeps randomly returning 500 status code or a 200. Maybe something to check with them.
