### ISSUE TITLE
Send success notification if `Flow1-1` succeeds

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#24]
## Background, context, and business value
Related to issue #23 , but now we want to send success notifications. 

## The specific request, in as few words as possible
If job `Flow 1-1` succeeds (https://www.openfn.org/projects/p5am6e/jobs/jywr9p), then send this notification to DTP: 
```
  {
        status: 'Pending Acknowledgement',
        primero_user: state.data.interventions[0].owned_by,
        case_id: state.data.interventions[0].case_id,
        progres_interventionnumber: state.data.interventions[0].progres_interventionnumber
    }
```

## trigger
Flow job that runs ONLY if Flow1-1 succeeds
form-name"}`

## expression.js
New job `Flow1-4` that should looks very similar to this job `Flow1-3` and send to the same DTP endpoint: https://www.openfn.org/projects/p5am6e/jobs/jyp94p

## state.json
See LP for DTP certificate

Sample Message that was successfully uploaded to Primero in job Flow1-1, and therefore should trigger a successful notification to be sent back to DTP: 
https://www.openfn.org/projects/p5am6e/messages/mwbmaa6v

## output.json
https://github.com/OpenFn/primero-progres/blob/master/sampleData/successNotificationToDTP.json

## TO TEST
Please run this new job against this Message on Prod: https://www.openfn.org/projects/p5am6e/messages/m66rga5j

**Comment by lakhassane** [comment]
@aleksa-krolls this is implemented.

**Comment by aleksa-krolls** [comment]
@lakhassane I've turned on the job to test, and see this is failing with TypeError: https://www.openfn.org/projects/p5am6e/runs/r6g47j76

Feel free to test on prod - see Message link above to trigger this.

**Comment by lakhassane** [comment]
Find correction and green check: https://www.openfn.org/projects/p5am6e/runs/ryawp8e7
