### ISSUE TITLE
New jobs for UNHCR Progres to UNICEF Primero  sync - FLOW 1 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-progres#3]
## Background, context, and business value

UNICEF  and UNHCR  are building an interoperability layer between their two systems, Primero and Progres, in order to reduce inefficient, insecure, and duplicative data entry processes. OpenFn will sync the cases and referrals between these two systems. 

Example: As a UNICEF caseworker, I would like to electronically send a referral for a case to UNHCR. I would also like to receive an update on the referral decision.

## The specific request, in as few words as possible

See the [data flow diagrams](https://lucid.app/lucidchart/12015c2c-84e7-4e27-ae98-d70ea888cdef/edit?page=iv1~CT.FK-.F#) --> Note there are multiple tabs! **This issue is for FLOW 1**
See the [mapping sheet](https://docs.google.com/spreadsheets/d/1b3yaEN_eSsEswJKoNo0FercWwLJp-8PZyWxq4wETnP4/edit#gid=1824703789) for field mappings and lookup tables. 

**Authentication**: 
`get('https://dtp.unhcr.org/api/sslCertCheck', {
  agentOptions: { ca: state.configuration.privateKey },
});`

**Flow 1: Progres --> Primero** 

Progres will post data to the OpenFn inbox to start this flow. 

Create Job 1 which cleans up and maps the Progres extract sent to the OpenFn inbox and upserts to Primero
Upserting to Primero ... _for these steps below, can we leverage the `upsertCases(...)` helper function?_
1. search for existing cases: `GET /api/v2/cases/:id` first using the field `progres_primeroid` & if no results are returned use `progres_individual.progres_id`
2. update an existing case and upsert referral: `PATCH /api/v2/cases/:id`
3. if case not found, create a new case and referral: `POST /api/v2/cases`

Create Job 2 which GETS status updates from Primero and send the referral decision to DTP:
1. Get referral decision: `GET /api/v2/cases/:id` -- from the field `status`
- _can we use the `getCases(...)` helper function?_
- Only get cases that have been updated since the last fetch. This should run daily. 
2. Generate JSON payload based on the case data. [Sample referral decision message](https://github.com/OpenFn/primero-progres/blob/master/sampleData/flow1__progresReferralConfirmation.json) to be sent to `https://antirrio.azure-api.net/primero-uat/ReceiveDecisionOutgoingReferral`

## state.json
Progres/DTP - Use the certificate
Primero - See LP for `Primero Dadaab`

[Sample JSON](https://www.openfn.org/projects/p5am6e/messages/mv76jqgg) 

## adaptor

HTTPS adaptor to post to DTP ? 
Primero adaptor
[Primero API Docs](https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api)
 

## trigger

Job 1: Message filter - upon receiving a message from DTP
Job 2: Scheduled daily job 

## expression.js

2 jobs...

1. Clean and map DTP extract and upsert in Primero
2. Fetch for Primero referral decision and send to DTP

## output.json

Sample output for jobs: 
1. [Sample JSON to be uploaded to Primero](https://github.com/OpenFn/primero-progres/blob/master/sampleData/primero_sample_state.json)
2. [Sample DTP referral decision message](https://github.com/OpenFn/primero-progres/blob/master/sampleData/flow1__progresReferralConfirmation.json) to be sent to `https://antirrio.azure-api.net/primero-uat/ReceiveDecisionOutgoingReferral`

**Comment by aleksa-krolls** [comment]
@lakhassane This is the first Progres issue that involves posting data to DTP - see my issue #4 re: authentication. 

Please liaise with @daissatou2 if you have any questions :)

**Comment by lakhassane** [comment]
@daissatou2 I might need a bit more context on field that says `See F1. Service Mapping (V4 to Primero)`. I don't understand that tab and their use in the mapping.

**Comment by aleksa-krolls** [comment]
@lakhassane I added some examples to the mapping sheet. Basically, Progres might send us 2 field values (an `intervention` and `intervention_type`)... we need to use both to determine the 1 Primero `service_type` to output.

**Comment by lakhassane** [comment]
@aleksa-krolls @daissatou2 I pushed a draft of the job 1. However, I left a couple of comments in the code that I might need help with.
For example the field `language`has a bunch of progres value in the column `C` what value could be used to map with the tab Language.

**Comment by aleksa-krolls** [comment]
fantastic @lakhassane. We just got a new version of state from UNHCR, can you please test with this? 
https://www.openfn.org/projects/p5am6e/messages/mmq3jvbd

@daissatou2 please work with Mamadou to answer any questions and to setup this job on OpenFn. You can configure the job, creds (`Primero Dadaab Demo (open_function)`), and adaptor and send him a link to connect with Github. 

For testing...
1. We should be able to run the above message through the flow to create a new `Case` with `Services` in Primero. 
2. You can then log into Primero and update the status to "accepted" as a caseworker might do. 
3. Then we should be able to run the second half of this flow to send a decision back to DTP.
If we successfully get through the above steps, you can them email the DTP team (see email chain `Open Fn PRIMERO Testing`) to ask them to confirm they got a decision.

**Comment by aleksa-krolls** [comment]
@lakhassane To clarify the credentials 
- Primero (see LP for `Primero Dadaab`)
- DTP (see LP for `UNHCR Subscription` & then also include certificate thumbprint)

**Comment by daissatou2** [comment]
@lakhassane please use this job that I set up: https://www.openfn.org/projects/p5am6e/jobs/jywr9p

**Comment by lakhassane** [comment]
Thanks @daissatou2. By the way, I forgot to ask yesterda, should we use the same data to upsert the cases, and to upsert the referrals? I don't know how primero works on the referral side and I might need a bit of help.

**Comment by lakhassane** [comment]
@aleksa-krolls Im trying to create a case but bumping on a `403 forbidden`that is not say we don't have the permission to do so. Something worth asking the client?
cc: @taylordowns2000

**Comment by aleksa-krolls** [comment]
@lakhassane Some changes here for `jobs/1.upsertExtracts.js` when we upload referrals to Primero...

We have an updated `state.json` from DTP that groups referrals in an `interventions[*]` array: https://github.com/OpenFn/primero-progres/blob/master/sampleData/progres_outboundReferral.json

This notification should trigger OpenFn to upsert cases in Primero. I tried to adjust the job to support this array, but failed to implement a `forEach(...)`. See run failure: https://www.openfn.org/projects/p5am6e/runs/rj5zre55

### To test
See LP for `Primero Dadaab (open_function API-only user)`
Re-run this on production please: https://www.openfn.org/projects/p5am6e/runs/rj5zre55

**Comment by lakhassane** [comment]
Ah @aleksa-krolls the issue here was you used an `each` that was already looping accross the `interventions` array so no need to use a `forEach`. Im removing it now.

Just to confirm if we have two object in interventions, we need to send two calls to create/update case right?

**Comment by aleksa-krolls** [comment]
@lakhassane I see a new failure for this job on a Message/Intervention that was just sent by DTP to the OpenFn Inbox. Can you please take a look to troubleshoot `jobs/1.upsertExtracts.js`?  
Run failure: https://www.openfn.org/projects/p5am6e/runs/r9wxpm6j
Message: https://www.openfn.org/projects/p5am6e/messages/mpq7bwn6
