### ISSUE TITLE
Flow1-1: Update `registration_date` format

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#33]
## Request
The current ISO date that sets `registration_date = today()` doesn't work. See hardcode example data value that does: 
https://github.com/OpenFn/primero-progres/blob/635378f8ce9acd53600965b4fe2363e4f8c76711/jobs/1.upsertExtracts.js#L488-L489

## state
See LP for `Primero Gambella open_function API user`
https://www.openfn.org/projects/p5am6e/messages/061517a0-6ce0-70fd-b63c-13336bfa8be1

## expression
`jobs/1.upsertExtracts.js`

## adaptor 
Primero

**Comment by lakhassane** [comment]
@aleksa-krolls green check here: https://www.openfn.org/projects/p5am6e/runs/06155bf8-4639-7ab8-b2f2-18b154dfe912

New case created with the right `registration_date` (see on postman): `d115bb50-4080-497a-ac01-71799fadf09c`.
