### ISSUE TITLE
Flow 2-2: Add service `unique_id` substring to `id`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#34]
## Request
Current mapping returns a string that is 73 characters long. 
`id: ${case_id}#${service.unique_id}`

The field `id` needs to be 49 characters long, following the format `{case_id}#{service_uid}`. 
However, the service `unique_id` is a very long string, so we want to take a substring of the **last 12 digits of `service.unique_id`** to append to the case_id so that...
`id: ${case_id}#${service_uid_substring}`
id: "43597a1b-fff9-4602-99d7-bcc0bc8a917b#**eb097be51d89**"

## expression
Please update this line: 
https://github.com/OpenFn/primero-progres/blob/cea89cbce48efe56502e91268e945a13fe869953/jobs/2.b.uploadReferrals.js#L239

## state
see job: https://www.openfn.org/projects/p5am6e/jobs/jydbjq
see msg: https://www.openfn.org/projects/p5am6e/messages/060f5694-8000-7dc1-a858-af7d440123e9

See sample response to job Flow 2-1 when we get cases from Primero: https://github.com/OpenFn/primero-progres/blob/master/sampleData/getPrimeroCases.json#L56

## adaptor
http

**Comment by lakhassane** [comment]
I made the change @aleksa-krolls see screenshot

<img width="485" alt="Screen Shot 2021-09-30 at 13 05 46" src="https://user-images.githubusercontent.com/8411231/135460698-6a505588-b254-4c89-b25d-d55f5e139f6c.png">
