### ISSUE TITLE
Flow2-2: Invalid time value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#35]
## Request
In testing, seeing this error: `RangeError [Error]: Invalid time value`
https://www.openfn.org/projects/p5am6e/runs/06155e28-2241-7198-96ad-1bc3c58afd7f

Feel free to re-run on prod. 
 
## expression
`jobs/2.b.uploadReferrals.js`

## state
`open_function` user should now have all the appropriate access - see job: https://www.openfn.org/projects/p5am6e/jobs/jydbjq

Message: https://www.openfn.org/projects/p5am6e/messages/06155e28-0908-7ca9-b726-05fc4cfa93c2

**Comment by lakhassane** [comment]
@aleksa-krolls issue with date_of_birth. It's failing now with some unhcr issue

https://www.openfn.org/projects/p5am6e/runs/06155ea0-5995-7e4d-802e-6c1b399b5592
