### ISSUE TITLE
Test UNHCR authentication

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#4]
Using the SSL cert we just created, [here](https://github.com/OpenFn/primero-progres/blob/master/sampleData/flow1__progresReferralConfirmation.json) is a payload you can post to this endpoint: 
https://antirrio.azure-api.net/primero-uat/ReceiveDecisionOutgoingReferral

Let me know ASAP if that works. @taylordowns2000 is on an email chain with UNHCR and can ask their team any direct questions if needed.

**Comment by taylordowns2000** [comment]
@lakhassane , include the header `Ocp-Apim-Subscription-Key` with the value I've shared privately.

**Comment by aleksa-krolls** [comment]
@lakhassane I've asked UNHCR to confirm they received your post. If you're getting `200`s, assume it's working for now :)
