### ISSUE TITLE
False success: Primero `500` error is showing as successful run in OpenFn

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#41]
## Describe the bug
See the false success run: https://www.openfn.org/projects/p5am6e/runs/0616ecab-7553-7af0-abf6-5708f4b129a4
```
Fetching by case id...
(node:16452) UnhandledPromiseRejectionWarning: Error: Server responded with:
{
  "statusCode": 500,
  "body": "{\"errors\":[{\"status\":500,\"resource\":\"/api/v2/cases\",\"message\":\"No field configured for Child with name 'case_id'\"}]}", 
```
  
## To Reproduce
Feel free to re-run on prod. 
We expect this to find the matching case & referral... and update the referral status in Primero. 

### adaptor
language-primero@2.3.3

### expression.js
jobs/2.c.uploadDecisionsV2.js

### state.json
See LP for `Primero Gambella open_function API user`
https://www.openfn.org/projects/p5am6e/messages/0616ecab-5cad-7810-b6d0-9cf8011c19d4

**Comment by aleksa-krolls** [comment]
@lakhassane Okay, cool. Noted re: `v2.3.4`! 

Now can you help me solve the `500` error :-) 
This was working before... see example successful run below: 
https://www.openfn.org/projects/p5am6e/runs/06168c23-52ed-728d-907e-9ff85d13cf25

**Comment by lakhassane** [comment]
@alek if they deployed the fix this issue should auto-solve I would say.
Im having a green check here: https://www.openfn.org/projects/p5am6e/runs/06181305-b1c5-77c9-bb7d-415da46b3a7b

But no cases. Also not hitting `500` with postman anymore.

**Comment by aleksa-krolls** [comment]
@lakhassane It looks like this `case_id` query doesn't work if cases were created _before_ the patch fix. I've reached out to Quoin. 
cc @daissatou2 pls ask me about this

In the meantime, I have it working for a more recent case here: https://www.openfn.org/projects/p5am6e/runs/061813fb-3cad-7e6f-a32b-1a39bdf9c21d

**Request:** If case is NOT found, can you please throw an error and force the job to fail with the error `No case found. Referral decision cannot be synced`? 
Here is a sample state: https://www.openfn.org/projects/p5am6e/messages/0616ecab-5cae-7297-ab0e-5a9c19b4d3a2

**Comment by lakhassane** [comment]
@aleksa-krolls throwing error when case not found: https://www.openfn.org/projects/p5am6e/runs/06181a4d-cdad-7066-956a-d1940c80efbc

**Comment by aleksa-krolls** [comment]
@lakhassane Looking great, thank you!
