### ISSUE TITLE
Update how we get referrals in Flow 2: Primero-> Progres

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/primero-progres#42]
## Background, context, and business value

Update `Flow 2: Primero-> Progres` in how we get referral data from Primero ([Flow 2-1](https://github.com/OpenFn/primero-progres/blob/master/jobs/2.a.getCases.js))

Currently in job Flow 2-1,  on a scheduled basis OpenFn...
- **Step 1:** Gets cases from Primero that have been recently updated. See [filtering criteria](https://github.com/OpenFn/primero-progres/blob/master/jobs/2.a.getCases.js). This returns JSON response that includes data for cases and related services. 
- **Step 2:** And then filters for Services that have been recently updated.

**However, we learned that the service date is not updated when the "REFER" button is clicked on the frontend. So there is no way to get the most recent referrals with this current implementation.** 

## The specific request, in as few words as possible

See data flow diagram: https://lucid.app/lucidchart/c12010a3-c6a9-4169-bd02-16a3b7d29e57/edit?invitationId=inv_665431b4-228d-45bc-88e5-3b4779964ea1&page=jK.jmqob8Sa0#

We will need to **replace step 2 above** with new steps that will...
2. Get referrals for the cases returned in the step 1 `getCases(..)` request. 
`GET /api/v2/cases/:id/referrals` where `id` is each case record id returned in step 1.
This will return JSON like [this]( https://github.com/OpenFn/primero-progres/blob/master/sampleData/getPrimeroReferral.json).
3. Find new referrals: Filter for referrals where `created_at_date` is greater than or equal to the datetime of the last job run (or the manual cursor).
4. For each new referral, use the `service_record_id` ([see here](https://github.com/OpenFn/primero-progres/blob/master/sampleData/getPrimeroReferral.json#L14)) to then determine which service(s) from the step 1 [cases response](https://github.com/OpenFn/primero-progres/blob/master/sampleData/getPrimeroCases.json#L78) we should map & send to DTP. 

1 Service = 1 Referral... so this whole process will help us to determine how many and which services to send to Progres. 

## state.json
`Primero Gambella open_function`

## adaptor
Primero adaptor
[Primero API docs](https://github.com/primeroIMS/primero/tree/development_v2/app/controllers/api)

## expression.js
https://github.com/OpenFn/primero-progres/blob/master/jobs/2.a.getCases.js

## For testing
The job will basically determine...
Which Primero cases have been recently updated (getCases)? 
Which of these cases have new referrals (getReferrals for a case)? 
If new referrals found, which services to send to Progres (using service_record_id)?

**Comment by aleksa-krolls** [comment]
@daissatou2 Confirming this is looking good? Can we close this issue?
