### ISSUE TITLE
Flow2: Convert jobs to flow jobs

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#45]
## Background, context, and business value
In flow 2, currently we have 2 jobs that (1) fetch data from Primero & post to the OpenFn inbox, and then (2) send onwards to DTP. 
<img width="729" alt="Screen Shot 2021-12-13 at 9 11 06 AM" src="https://user-images.githubusercontent.com/16758106/145827617-1744ab0a-d389-4532-85d8-088dbe689aba.png">

## The specific request, in as few words as possible
Convert the job `Flow2-2` (`2.a.getCases.js`) to run as a flow job, triggered by job `Flow2-1` so that we can skip the step of posting Primero referral data to the OpenFn inbox. This will ensure better data security with no referrals on OpenFn servers when we move to prod. 

## state.json
Run `Flow2-1` job to trigger the flow: https://www.openfn.org/projects/primero-progres-v4-staging/jobs/jv7rnp
See LP for `Primero Gambella Demo - Get Referrals (open_function user)`

`Flow 2-2` - See LP for `UAT DTP - ReceiveIncomingReferral (open_function)`

## expression.js
Job 2-1: https://github.com/OpenFn/primero-progres/blob/master/jobs/2.a.getCases.js
Job 2-2 (to change to `flow` trigger): https://github.com/OpenFn/primero-progres/blob/master/jobs/2.b.uploadReferrals.js

**Comment by aleksa-krolls** [comment]
@lakhassane can you please prioritize this in the morning to unblock us before switching back to WCS? 
Let @daissatou2 know when ready for testing.

**Comment by lakhassane** [comment]
@daissatou2 this is ready for testing.
