### ISSUE TITLE
Data security feature: delete Messages from Inbox after processed

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#46]
## Background, context, and business value
To satisfy data security & privacy requirements, UNICEF requests that we do not keep data sent to OpenFn stored on our servers. However, for this implementation, UNHCR's system Progres sends receipts via HTTP POST requests to the OpenFn inbox to trigger different job flows. Therefore, they'd like to request deletion of these receipts once triggered runs have been completed. 

## The specific request, in as few words as possible
Implement automation to: 
1. Delete messages from Inbox after all related runs* have been completed (no matter if these runs fail or succeed). This assumes we will rely on UNHCR to re-send payloads if we need to retry a transactions. 
2. Delete messages from Inbox where no runs are triggered. (If data is sent to OpenFn inbox, and no runs are triggered - i.e., the job is "off", then automatically delete the Message to ensure security.)

For any runs completed, these should not be deleted (even if the parent Message is) for 365 days and remain accessible via Activity History. 

_*Note that this project has multiple flow jobs triggered by messages received from Proges._ 

## Resources
See drafted project docs: https://github.com/OpenFn/primero-progres
OpenFn project*: https://www.openfn.org/projects/primero-progres-v4-prod/jobs

## Testing Notes
They don't want to turn "on" this feature until the official go-live and plan to do some production testing before then (during which it _will_ be helpful to keep things as is so we can inspect messages as needed for troubleshooting). Therefore, is there a way to toggle on/off this feature? Otherwise, how do you suggest we test/in what environment?

**Comment by aleksa-krolls** [comment]
@taylordowns2000 fyi - the client will be ready on Wednesday (Aug 24th) to implement this feature. Can you pls block time on your calendar accordingly to implement? Go-live will be the day after on the 25th. 

cc @daissatou2

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this is in your court for testing!

**Comment by aleksa-krolls** [comment]
@taylordowns2000 tested and working! And documented in the Project Security Configuration Checklist. Thank you!
