### ISSUE TITLE
Flow 1: New criteria for getting referral decisions from Primero

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#6]
## Background, context, and business value
See issue #3 for context on the data Flow 1: Progres referrals --> Primero. 
After a referral is uploaded to Primero, job `1.b.sendReferrals.js` will run daily to check Primero to see if case workers accepted/rejected this referral. The aim is to then notify DTP of the decision. 

## The specific request, in as few words as possible
When we `getCases(...)` from Primero, please update the search criteria to look for `cases` where...
1. `data.last_updated_at = Last 24 hours` AND `data.status !== 'open'` (because we're looking for `rejected` or `accepted` cases)... AND...
2. `data.services_section[...]` contains service where `progres_interventionnumber!==undefined` (because we only want to pull cases with referrals from UNHCR)

The `getCases(...)` step should find a case that looks something link this... however, note that sometimes there might be NO case decisions to send to DTP... handle for no data. 
https://github.com/OpenFn/primero-progres/blob/master/sampleData/primero_outboundReferral.json

We should then use this case data to map a decision to send to DTP 
https://github.com/OpenFn/primero-progres/blob/master/jobs/1.b.sendReferrals.js#L15-L22

**When done, please update this job, add a credential, and run this on prod to make sure this runs successfully.**
https://www.openfn.org/projects/p5am6e/jobs/jv89rx

## state.json
Primero: `Primero Dadaab (open_function API-only user)`
DTP: include security certificate and endpoint `https://antirrio.azure-api.net/primero-uat/ReceiveDecisionOutgoingReferral`

## adaptor
Not sure... primero or http? Please advise so that we can configure the job in OpenFn correctly. 

## trigger
Timer-based - we'll check for new referrals every X hours

## expression.js
https://github.com/OpenFn/primero-progres/blob/master/jobs/1.b.sendReferrals.js

## output.json
Send decision JSON to DTP like this:
https://github.com/OpenFn/primero-progres/blob/master/sampleData/progres_referralDecisionFromPrimero.json

**Comment by lakhassane** [comment]
@aleksa-krolls it is configured in prod: https://www.openfn.org/projects/p5am6e/runs/r9wxpdg4

**Comment by aleksa-krolls** [comment]
@lakhassane Question on this one... are you getting ALL Primero cases and then filtering? (I worry this will be hard to scale if the GET request returns hundreds of records.)
We should ideally...
1. Send a GET request to Primero where we have a query parameter filtering by `last_updated_at`. 
According to the [API docs](https://github.com/primeroIMS/primero/blob/development_v2/app/controllers/api/v2/docs/cases/get.md#query-for-cases) we should be able to filter by a date range... also we can configure these jobs to run daily, so that you can filter on where `last_updated_at: 2021-05-06` (YYYY-MM-DD). 
2. And then... of the subset of cases returned in the response, have the job filter to find only those cases with unhcr `services`

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Want to take a crack at improving this one? See my comment above... worried that this extract step will not work well when we have several cases to get from Primero.

**Comment by taylordowns2000** [comment]
@aleksa-krolls  (cc: @lakhassane ), this has been implemented, but i'm skeptical about using `today` as the filter. i'm also curious about state management here between runs. i'd rather implement that rather long process (is this an oppy for a new platform feature?!?) where we save the `lastSuccessfulRun` date and then use an "all items updated on that day or after" type of filter. this will make the job more complex, but seems to be what we're going for here.

@aleksa-krolls , please advise on how to move forward. it seems to be working as is, but could be better with the above and @lakhassane could implement that fairly easily by referencing other primero jobs.
