### ISSUE TITLE
Need improved error handling when custom error thrown

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#65]
## Describe the bug
[This run](https://www.openfn.org/projects/primero-progres-v4-prod/runs/064f7249-b83a-7fad-b52f-6e8c62f69dc8) doesn't show me the case `progres_interventionnumber` so I have no idea which record this error is related to. This error message needs to be updated to include system identifiers (progres_interventionnumber).
```
Error: Service value shared is not an accepted UNICEF service type. Please see the mapping specifications.
```

## To Reproduce
Run the job against this message: https://www.openfn.org/projects/primero-progres-v4-staging/messages/064f850c-6b81-7b25-8229-a7437cf3def2

### expression.js
Please make changes on a branch off of `main`, and submit PR to `staging` when ready to test. 

Link to the job itself in Github: https://github.com/OpenFn/primero-progres/blob/master/jobs/PROD/f1-1.sendReferralsToPrimero.js

### state.json

```json
{
  "configuration": ["SEE LAST PASS: 'Primero Gambella Demo [openfn testing]'"],
  "data": { https://www.openfn.org/projects/primero-progres-v4-staging/messages/064f850c-6b81-7b25-8229-a7437cf3def2 },
}
```

## Expected behavior
The run should fail against the message above but the log should include the `progres_interventionnumber`.

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].

**Comment by mtuchi** [comment]
@daissatou2 i have added the service and `progres_interventionnumber` on custom error message
