### ISSUE TITLE
sendDecision job fails with specific datetime cursor

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#80]
## Describe the bug
Since Jan 1st this job has been failing. [See run failure](https://v1.openfn.org/projects/primero-progres-v4-prod/runs/065f49ab-1122-7675-bea9-6f9f94eeed85) with cursor `2024-01-01T21:00:17.471Z..`

However, if we run the job with a more recent date cursor (e.g., `2024-04-09T00:00:00.000Z..`) then it works fine - [see successful run](https://v1.openfn.org/projects/primero-progres-v4-prod/runs/0661c232-df89-7a7a-be68-97fe34d2bb45). Can you take a look to see if you can figure out why? 

## To Reproduce
1. Run this job with the manualCursor `2024-01-01T21:00:17.471Z..`

### expression.js
https://github.com/OpenFn/primero-progres/blob/master/jobs/PROD/f1-2.sendDecisionToDTP.js

### state.json
Adaptor: `language-primero@2.3.5`. 
**Please be sure to remove any local state files once you're done testing.**

```json
{
  "configuration": ["SEE LAST PASS: 'DTP-sendDecision (PROD)'"],
  "cursor": "2024-01-01T21:00:17.471Z.."
}
```

## Expected behavior
Job should run successfully, even if there are no records to send to DTP.

**Comment by mtuchi** [comment]
@aleksa-krolls the run that has failed had a `504 Gateway Timeout` Error. 
>The 504 Gateway Timeout error is an [HTTP status code](https://www.lifewire.com/http-status-codes-2625907) that means that one server didn't receive a timely response from another server that it was accessing while attempting to load the web page or fill another request by the browser. In other words, 504 errors usually indicate that a different computer, one that the website you're getting the message on doesn't control but relies on, isn't communicating with it quickly enough.
