### ISSUE TITLE
Send each Primero referral as 1 Message to Inbox

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/primero-progres#9]
## Background
See issue #3 for original specs for Flow 2 (Primero referrals --> DTP). Currently the Get Primero extract job will return all referrals in 1 Message if multiple cases are found. See this example Message that includes multiple referrals: https://www.openfn.org/projects/p5am6e/messages/mrbpg7ej

## Request
Please only include 1 referral in each Message for optimized troubleshooting when we handoff to DTP in job 2.b.

## expression
Pls send 1 post to Inbox per referral here
https://github.com/OpenFn/primero-progres/blob/master/jobs/2.a.getCases.js#L21-L37

## output.json
Desired output example with only 1 referral... pls don't change the structure of the json object, just limit the items returned in the `_json` array. 
https://www.openfn.org/projects/p5am6e/messages/m58dmzk5

## To test
**Please re-run this on prod to verify:** https://www.openfn.org/projects/p5am6e/jobs/jv7rnp

**Comment by lakhassane** [comment]
@aleks I need a bit of clarification here.
Currently there is only one Message sent to inbox and it looks like this:

<img width="463" alt="Screen Shot 2021-05-10 at 12 37 57" src="https://user-images.githubusercontent.com/8411231/117660563-d6126680-b18c-11eb-9eeb-d66dfd821836.png">

So Im not sure what is the needed change.

**Comment by lakhassane** [comment]
And the job you linked on the **Test** section is different from the one in **expression** section.

**Comment by aleksa-krolls** [comment]
@lakhassane Sorry I confused myself. I updated the expression above. 
If you run [this job](https://www.openfn.org/projects/p5am6e/jobs/jv7rnp) above... you'll see that multiple referrals are being included in 1 Message ([see example](https://www.openfn.org/projects/p5am6e/messages/mrbpg7ej)). 
![image](https://user-images.githubusercontent.com/16758106/117665962-0c131300-b1ac-11eb-9d3b-40979a491636.png)
